import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import Footer from "./components/footer/Footer";

const roboto = Roboto({
  variable: "--roboto",
  subsets: ["latin", "cyrillic", "greek"], // Add required subsets
  weight: ["100", "300", "400", "500", "700", "900"], // Define required weights
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className + " antialiased bg-primary"}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
